# Generated by Django 5.0.6 on 2024-05-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
