# Generated by Django 5.0.6 on 2024-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
