# Generated by Django 5.0.6 on 2024-06-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0003_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.room', unique=True),
        ),
    ]
