# Generated by Django 5.0.6 on 2024-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0004_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='action',
        ),
        migrations.AddField(
            model_name='log',
            name='check_in_action',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='log',
            name='check_out_action',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
