# Generated by Django 5.0.6 on 2024-06-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0004_alter_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.room'),
        ),
    ]
