# Generated by Django 5.0.6 on 2024-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0005_remove_log_action_log_check_in_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
