# Generated by Django 5.0.6 on 2024-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0005_alter_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
