# Generated by Django 5.0.6 on 2024-06-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0006_alter_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(default=10000),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=1, max_digits=10)),
                ('guest_check_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.guest')),
            ],
        ),
    ]
