# Generated by Django 5.0.6 on 2024-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0007_room_room_price_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
