# Generated by Django 5.0.6 on 2024-06-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0009_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='guest_check_out',
        ),
        migrations.AddField(
            model_name='guest',
            name='revenue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.revenue'),
        ),
    ]
