# Generated by Django 5.0.6 on 2024-06-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0010_remove_revenue_guest_check_out_guest_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.revenue'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
