# Generated by Django 5.0.6 on 2024-06-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0012_alter_guest_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.revenue'),
        ),
    ]
