# Generated by Django 5.0.6 on 2024-06-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0013_alter_guest_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TestCompany', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkins',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AddField(
            model_name='guest',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AddField(
            model_name='log',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AddField(
            model_name='room',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
    ]
