# Generated by Django 5.0.6 on 2024-06-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0014_company_checkins_company_guest_company_log_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='TestCompany', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.suite'),
        ),
    ]
