# Generated by Django 5.0.6 on 2024-06-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0015_remove_room_room_price_remove_room_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
    ]
