# Generated by Django 5.0.6 on 2024-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0016_alter_room_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.BooleanField(default=False),
        ),
    ]
