# Generated by Django 5.0.6 on 2024-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0017_room_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='payment_action',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
