# Generated by Django 5.0.6 on 2024-06-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0018_guest_duration_log_payment_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='check_in_action',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='log',
            name='check_out_action',
        ),
        migrations.RemoveField(
            model_name='log',
            name='payment_action',
        ),
    ]
