# Generated by Django 5.0.6 on 2024-06-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0019_rename_check_in_action_log_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
    ]
