# Generated by Django 5.0.6 on 2024-07-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0020_staff_owner_alter_staff_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returning', models.BooleanField()),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=1, max_digits=10)),
                ('check_ins', models.IntegerField(blank=True, null=True)),
                ('check_outs', models.IntegerField(blank=True, null=True)),
                ('meta', models.CharField(max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.guest')),
            ],
        ),
    ]
