# Generated by Django 5.0.6 on 2024-07-12 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0020_staff_owner_alter_staff_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('staff', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='LodgeApp.guest')),
            ],
        ),
    ]
