<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-10 13:56
=======
# Generated by Django 5.0.6 on 2024-07-12 23:47
>>>>>>> c2af57d22ab157d6cb5f2bb43ee8bccca9b557c0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0020_staff_owner_alter_staff_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('returning', models.BooleanField()),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=1, max_digits=10)),
                ('check_ins', models.IntegerField(blank=True, null=True)),
                ('check_outs', models.IntegerField(blank=True, null=True)),
                ('meta', models.CharField(max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.guest')),
=======
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('staff', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='LodgeApp.guest')),
>>>>>>> c2af57d22ab157d6cb5f2bb43ee8bccca9b557c0
            ],
        ),
    ]
