# Generated by Django 5.0.6 on 2024-07-15 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0021_guesthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthistory',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.revenue'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
