# Generated by Django 5.0.6 on 2024-07-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0021_guesthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestHistory',
        ),
    ]
