# Generated by Django 5.0.6 on 2024-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0024_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
