# Generated by Django 5.0.6 on 2024-07-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0026_remove_room_room_number_room_room_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkins',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.revenue'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='log',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='room',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.company'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.suite'),
        ),
    ]
