# Generated by Django 5.0.6 on 2024-07-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0027_alter_checkins_company_alter_guest_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.room'),
        ),
    ]
