# Generated by Django 5.0.6 on 2024-07-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0028_alter_guest_room_alter_guesthistory_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LodgeApp.suite'),
        ),
    ]
