# Generated by Django 5.0.6 on 2024-07-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0031_alter_guest_room_alter_guesthistory_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LodgeApp.revenue'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LodgeApp.revenue'),
        ),
        migrations.AlterField(
            model_name='guesthistory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LodgeApp.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LodgeApp.suite'),
        ),
    ]
