# Generated by Django 5.0.6 on 2024-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0033_alter_checkins_time_alter_guest_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkins',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
