# Generated by Django 5.0.6 on 2024-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeApp', '0034_alter_checkins_time_alter_guest_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
